name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write

env:
  VITE_BACKEND_URL: https://localhost
  VITE_BACKEND_PORT: 3000
  VITE_FRONTEND_URL: https://localhost
  VITE_FRONTEND_PORT: 5173

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run build
        env:
          VITE_BACKEND_URL: https://localhost
          VITE_BACKEND_PORT: 3000
          VITE_FRONTEND_URL: https://loanrangers.github.io/SelfServiceLoaningFrontend/
          VITE_FRONTEND_PORT: 443

      - name: copy
        run: cp -r /home/runner/work/SelfServiceLoaningFrontend/SelfServiceLoaningFrontend/dist /home/runner/actions_github_pages_1746625526442

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: List files
        run: ls -R /home/runner/work/SelfServiceLoaningFrontend/SelfServiceLoaningFrontend/dist
