name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  VITE_BACKEND_URL: https://localhost
  VITE_BACKEND_PORT: 3000
  VITE_FRONTEND_URL: https://localhost
  VITE_FRONTEND_PORT: 5173

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run build
        env:
          VITE_BACKEND_URL: https://localhost
          VITE_BACKEND_PORT: 3000
          VITE_FRONTEND_URL: https://loanrangers.github.io/SelfServiceLoaningFrontend/
          VITE_FRONTEND_PORT: 443

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
